before_install:
  - gem install bundler
before_script:
  # enable ipv6 see: https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350497804
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
language: ruby
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: 1.9.3
    - rvm: jruby
    - rvm: rbx-3.2
    - rvm: ree
  fast_finish: true
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby
  - rbx-3.2
  - ree
script: 
  - "bundle exec shindont"
  - "bundle exec rake spec[progress]"
sudo: false
